<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFrameworks>netstandard2.0;net10.0</TargetFrameworks>
        <LangVersion>14.0</LangVersion>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <PackageReference Include="QcomImageUtils" Version="2026.8.8-g32680cb" />
    </ItemGroup>

</Project>
